### ISSUE TITLE
Have you had any success getting a response from /search-entries with 'password' as source?

### ISSUE THREAD

**Issue by StephenArg** [HannoZ/Lexicala.NET#8]
I'm on day 2 of trying to use this API and I think I've realized that the source I need to use to convert English to Italian is 'password', but I can't seem to get it to work. for example: '/search-entries?source=password&text=sweet&language=en' doesn't return any results.
Do you have any idea what I might be doing wrong? I'm having trouble finding any other relevant information on this API. My google search brought me to your .NET client, so I'm hoping you might know.

Here's the full request in C#:

```var client = new HttpClient();
var request = new HttpRequestMessage
{
	Method = HttpMethod.Get,
	RequestUri = new Uri("https://lexicala1.p.rapidapi.com/search-entries?text=sweet&language=en&source=password"),
	Headers =
	{
		{ "X-RapidAPI-Key", "api-key" },
		{ "X-RapidAPI-Host", "lexicala1.p.rapidapi.com" },
	},
};
using (var response = await client.SendAsync(request))
{
	response.EnsureSuccessStatusCode();
	var body = await response.Content.ReadAsStringAsync();
	Console.WriteLine(body);
}
```

**Comment by HannoZ** [comment]
Hi Stephen, I am not familiar with the password dictionary, I've only used the global dictionary. But I also see that there have been some changes to the API, the base URL was changed from https://dictapi.lexicala.com to https://lexicala1.p.rapidapi.com and uses an API key now instead of basic auth (username + password) (but the old api still works, so I never noticed it) 

So I it will take me some time to rewrite some stuff to update to the new api. 
Having said that, using the old apiI also don't get any search results when searching in the password dictionary, so I think your code is be correct, but there is some other issue why it's not working. So I suggest to contact Lexicala support for this (and let me know if they have an answer for you :) )

**Comment by StephenArg** [comment]
Thanks for the response! I'll ask them how to get search results in the Password dictionary and if I hear anything I'll try to remember to let you know

**Comment by StephenArg** [comment]
As I was writing my email this morning about the Password dictionary it just started working. I'm not sure what changed since I used the same parameters, but give it a try with the new api base url and let me know if it works for you too

**Comment by HannoZ** [comment]
Yes same here, it works now with the old api version. So I'll close this issue then
